"""Add OrderItem model and update Order schema for cart

Revision ID: a5d0b977095d
Revises: 47fdea7bb183
Create Date: 2025-07-21 21:03:56.420637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d0b977095d'
down_revision = '47fdea7bb183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('product_variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('product_variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
