"""Add ProductVariant model and update product schema

Revision ID: a9d09d1645d0
Revises: 68e46cc110b2
Create Date: 2025-07-19 13:12:44.844480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d09d1645d0'
down_revision = '68e46cc110b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_value', sa.Float(), nullable=False),
    sa.Column('quantity_unit', sa.String(length=20), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('buying_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('buying_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buying_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))

    op.drop_table('product_variant')
    # ### end Alembic commands ###
