"""Add expiry_date and supplier to ProductVariant

Revision ID: af702c65f89e
Revises: fd011555c5d9
Create Date: 2025-07-22 16:48:01.283487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af702c65f89e'
down_revision = 'fd011555c5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('supplier', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_column('supplier')
        batch_op.drop_column('expiry_date')

    # ### end Alembic commands ###
