"""Final Order-OrderItem relationship fix (removed duplicate)

Revision ID: fd011555c5d9
Revises: 31233fb83ed4
Create Date: 2025-07-22 13:52:25.102398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd011555c5d9'
down_revision = '31233fb83ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=False, server_default='Pending'))

    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_level', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_column('stock_level')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
